### ISSUE TITLE
If query topic is a blacklisted topic, querying fails

### ISSUE THREAD

**Issue by corbfost** [Lingistic/GraBTax#5]
https://github.com/Lingistic/GraBTax/blob/master/lib/build_graph.py#L288

Above line attempts to grab the weight of the query topic from the graph, but if that topic has been blacklisted from the graph, it fails. Cannot be fixed without re-building the graph without blacklisted topics. 

Try querying using "disease" for an example

**Comment by robmcdan** [comment]
So it seems to me that you shouldn't be using a query topic which doesnt exist in the graph -- blacklisted topics should be treated as if they just don't exist. 

I've added a check in recursive_partition to return immediately if the query topic doesn't exist. My suggestion is that you should check if your query string contains blacklisted topics and remove them (or consider un-blacklisting the topic and rebuilding the graph.
